runtime::test_idev_id_cert: Fix flaky test.
This test was assuming that BigNumRef::to_vec() would pad out the number
to 48 bytes, which it doesn't. Use BigNumRef::to_vec_padded(48) instead.

Example Failure:

```
---- integration_tests::test_idev_id_cert stdout ----
thread 'integration_tests::test_idev_id_cert' panicked at 'source slice length (47) does not match destination slice length (48)', runtime/tests/runtime_integration_tests/integration_tests.rs:1081:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````