CI: Disable fuzz build tests.
These intermittently crash:

```
error: failed to run custom build command for `openssl-sys v0.9.93`

Caused by:
  process didn't exit successfully: `/home/runner/work/caliptra-sw/caliptra-sw/dpe/dpe/fuzz/target/debug/build/openssl-sys-f4822ba2ff559cb6/build-script-main` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
```